// Package hotreload is func library that implement reload service on development stage.
// # This manifest was generated by ymir. DO NOT EDIT.
package hotreload

import (
	"fmt"
	"io"
	"os/exec"
	"syscall"

	"github.com/creack/pty"
)

func (w *worker) execCmd(command string, options ...string) (
	*exec.Cmd, io.ReadCloser, io.ReadCloser, error) {
	// Checking for nil.
	if command == "" || options == nil {
		return nil, nil, nil, fmt.Errorf("no command to execute")
	}

	// Collect command line.
	var args = append([]string{"-c", command}, options...)
	cmd := exec.Command("/bin/sh", args...) // #nosec G204
	p, err := pty.Start(cmd)
	if err != nil {
		return nil, nil, nil, err
	}
	return cmd, p, p, err
}

func (w *worker) killCmd(cmd *exec.Cmd) (pid int, err error) {
	pid = cmd.Process.Pid
	err = syscall.Kill(-pid, syscall.SIGKILL)
	_, _ = cmd.Process.Wait()
	return
}
