// Package hotreload is func library that implement reload service on development stage.
// # This manifest was generated by ymir. DO NOT EDIT.
package hotreload

import (
	"context"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sync"
	"time"

	"github.com/rs/zerolog"

	"github.com/fsnotify/fsnotify"
)

const timeoutDuration = 200 * time.Millisecond

// Watcher abstract of fileWatcher instances.
type Watcher interface {
	Start(ctx context.Context)
	Stop() error
	Add(filename string) error
	EventsCh() chan *FileWatcherEvent
}

type fileWatcher struct {
	watcher          *fsnotify.Watcher
	configFiles      map[string]*watchedFile
	configFilesLock  sync.RWMutex
	logger           zerolog.Logger
	reconcileTimeout time.Duration
	cancel           context.CancelFunc
	done             chan any
	stopOnce         sync.Once

	// eventsCh Channel where an event will be emitted when a file change is detected
	// a call to Start is needed before any event is emitted
	// after a Call to Stop succeed, the channel will be closed
	eventsCh chan *FileWatcherEvent
}

// EventsCh return watcher channel.
func (w *fileWatcher) EventsCh() chan *FileWatcherEvent {
	return w.eventsCh
}

type watchedFile struct {
	modTime time.Time
}

// FileWatcherEvent event watcher data.
type FileWatcherEvent struct {
	Filenames []string
}

// NewFileWatcher create a file watcher that will watch all the files/folders from configFiles
// if success a fileWatcher will be returned and a nil error
// otherwise an error and a nil fileWatcher are returned.
func NewFileWatcher(dirs []string, logger zerolog.Logger) (Watcher, error) {
	ws, err := fsnotify.NewWatcher()
	if err != nil {
		return nil, err
	}
	w := &fileWatcher{
		watcher:          ws,
		logger:           logger,
		configFiles:      make(map[string]*watchedFile),
		eventsCh:         make(chan *FileWatcherEvent),
		reconcileTimeout: timeoutDuration,
		done:             make(chan any),
	}
	for _, f := range dirs {
		err = w.Add(f)
		if err != nil {
			return nil, fmt.Errorf("error adding file %q: %w", f, err)
		}
	}

	return w, nil
}

// Start a file watcher, with a copy of the passed context.
// calling Start multiple times is a noop.
func (w *fileWatcher) Start(ctx context.Context) {
	if w.cancel == nil {
		cancelCtx, cancel := context.WithCancel(ctx)
		w.cancel = cancel
		go w.watch(cancelCtx)
	}
}

// Stop the file watcher.
// calling Stop multiple times is a noop, Stop must be called after a Start.
func (w *fileWatcher) Stop() error {
	var err error
	w.stopOnce.Do(func() {
		w.cancel()
		<-w.done
		err = w.watcher.Close()
	})
	return err
}

// Add a file to the file watcher.
// Add will lock the file watcher during the add.
func (w *fileWatcher) Add(filename string) error {
	filename = filepath.Clean(filename)
	w.logger.Info().Str("file", filename).Msg("adding files")
	var addFunc = func(fl string) error {
		if err := w.watcher.Add(fl); err != nil {
			return err
		}
		modTime, err := w.getFileModifiedTime(fl)
		if err != nil {
			return err
		}
		w.addFile(fl, modTime)
		return nil
	}
	var st, _ = os.Stat(filename)
	if st.IsDir() {
		return filepath.Walk(filename, func(ph string, i fs.FileInfo, err error) error {
			if i.IsDir() {
				return nil
			}
			return addFunc(ph)
		})
	}
	return addFunc(filename)
}

func (w *fileWatcher) addFile(filename string, modTime time.Time) {
	w.configFilesLock.Lock()
	defer w.configFilesLock.Unlock()
	w.configFiles[filename] = &watchedFile{modTime: modTime}
}

func (w *fileWatcher) watch(ctx context.Context) {
	var ticker = time.NewTicker(w.reconcileTimeout)
	defer ticker.Stop()
	defer close(w.done)
	defer close(w.eventsCh)

	for {
		select {
		case event, ok := <-w.watcher.Events:
			if !ok {
				w.logger.Warn().Msg("watcher event channel is closed")
				return
			}
			if err := w.handleEvent(ctx, event); err != nil {
				w.logger.Error().Err(err).Interface("event", event).Msg("error handling watcher event")
			}
		case err, ok := <-w.watcher.Errors:
			if !ok {
				w.logger.Error().Err(err).Msg("watcher error channel is closed")
				return
			}
		case <-ticker.C:
			w.reconcile(ctx)
		case <-ctx.Done():
			return
		}
	}
}

func (w *fileWatcher) reconcile(ctx context.Context) {
	w.configFilesLock.Lock()
	defer w.configFilesLock.Unlock()
	for filename, configFile := range w.configFiles {
		newModTime, err := w.getFileModifiedTime(filename)
		if err != nil {
			w.logger.Error().Err(err).Str("file", filename).Msg("failed to get file modTime")
			continue
		}

		err = w.watcher.Add(filename)
		if err != nil {
			w.logger.Error().Err(err).Str("file", filename).Msg("failed to add file to watcher")
			continue
		}
		if !configFile.modTime.Equal(newModTime) {
			w.logger.Info().Str("file", filename).
				Time("old modTime", configFile.modTime).
				Time("new modTime", newModTime).Msg("call the handler")
			configFile.modTime = newModTime
			select {
			case w.eventsCh <- &FileWatcherEvent{Filenames: []string{filename}}:
			case <-ctx.Done():
				return
			}
		}
	}
}

func (w *fileWatcher) handleEvent(ctx context.Context, event fsnotify.Event) error {
	// we only want to Create and Remove events to avoid triggering a reload on file modification
	if !isCreateEvent(event) && !isRemoveEvent(event) && !isWriteEvent(event) && !isRenameEvent(event) {
		return nil
	}
	filename := filepath.Clean(event.Name)
	configFile, basename, ok := w.isWatched(filename)
	if !ok {
		return fmt.Errorf("file %s is not watched", event.Name)
	}

	// we only want to update mod time and re-add if the event is on the watched file itself
	if filename == basename {
		if isRemoveEvent(event) {
			// If the file was removed, try to reconcile and see if anything changed.
			w.logger.Info().
				Str("filename", event.Name).
				Str("OP", event.Op.String()).Msg("attempt a reconcile ")
			configFile.modTime = time.Time{}
			w.reconcile(ctx)
		}
	}
	return nil
}

func (w *fileWatcher) getFileModifiedTime(filename string) (time.Time, error) {
	fileInfo, err := os.Stat(filename)
	if err != nil {
		return time.Time{}, err
	}

	return fileInfo.ModTime(), err
}

func (w *fileWatcher) isWatched(filename string) (*watchedFile, string, bool) {
	path := filename
	w.configFilesLock.RLock()
	configFile, ok := w.configFiles[path]
	w.configFilesLock.RUnlock()
	if ok {
		return configFile, path, true
	}

	stat, err := os.Lstat(filename)

	// if the error is a not exist still try to find if the event for a configured file
	if os.IsNotExist(err) || (!stat.IsDir() && stat.Mode()&os.ModeSymlink == 0) {
		// try to see if the watched path is the parent dir
		newPath := filepath.Dir(path)
		w.configFilesLock.RLock()
		configFile, ok = w.configFiles[newPath]
		w.configFilesLock.RUnlock()
	}
	return configFile, path, ok
}

func isCreateEvent(event fsnotify.Event) bool {
	return event.Op&fsnotify.Create == fsnotify.Create
}

func isRemoveEvent(event fsnotify.Event) bool {
	return event.Op&fsnotify.Remove == fsnotify.Remove
}

func isWriteEvent(event fsnotify.Event) bool {
	return event.Op&fsnotify.Write == fsnotify.Write
}

func isRenameEvent(event fsnotify.Event) bool {
	return event.Op&fsnotify.Rename == fsnotify.Rename
}
