// Package hotreload is func library that implement reload service on development stage.
// # This manifest was generated by ymir. DO NOT EDIT.
package hotreload

import (
	"context"
	"os"

	"github.com/rs/zerolog"
)

// Option is Configure type return func.
type Option = func(c *Options) error

// Options is data structure for hotreload initialize.
type Options struct {
	Dirs   []string
	Logger zerolog.Logger
}

func Start(opts ...Option) (func() error, error) {
	var o = &Options{}
	for _, opt := range opts {
		err := opt(o)
		if err != nil {
			panic(err)
		}
	}
	var (
		l      = o.Logger
		wd, _  = os.Getwd()
		w, err = NewFileWatcher(o.Dirs, o.Logger)
	)
	if err != nil {
		l.Error().Err(err).Msg("initialize hotreload is failed")
		return nil, err
	}
	w.Start(context.Background())
	go func() {
		var wr = NewWorker(wd)
		if err = wr.Run(); err != nil {
			l.Error().Err(err).Msg("+++")
			return
		}
		for event := range w.EventsCh() {
			l.Info().Strs("event:", event.Filenames).Msg("+++")
			wr.Reload()
			if err = wr.Run(); err != nil {
				l.Error().Err(err).Msg("+++")
				continue
			}
		}
	}()
	return w.Stop, err
}

// WithDirs will assign to field dirs Configure.
func WithDirs(dirs []string) Option {
	return func(c *Options) error {
		c.Dirs = dirs
		return nil
	}
}

// WithLogger will assign to field logger Configure.
func WithLogger(log zerolog.Logger) Option {
	return func(c *Options) error {
		c.Logger = log
		return nil
	}
}
