// Package sqlite is library function for dialect sqlite db driver.
// # This manifest was generated by ymir. DO NOT EDIT.
package sqlite

import (
	"database/sql"
	"database/sql/driver"

	"modernc.org/sqlite"
)

type CGOFreeSqliteDriver struct {
	*sqlite.Driver
}

type sqlite3DriverConn interface {
	Exec(string, []driver.Value) (driver.Result, error)
}

func (d CGOFreeSqliteDriver) Open(name string) (conn driver.Conn, err error) {
	conn, err = d.Driver.Open(name)
	if err != nil {
		return nil, err
	}
	_, err = conn.(sqlite3DriverConn).Exec("PRAGMA foreign_keys = ON;", nil)
	if err != nil {
		_ = conn.Close()
		return nil, err
	}
	return conn, err
}

func init() {
	sql.Register("sqlite3", CGOFreeSqliteDriver{Driver: &sqlite.Driver{}})
}
