// Package driver is library function for whole system.
// # This manifest was generated by ymir. DO NOT EDIT.
package driver

import (
	"database/sql/driver"

	"modernc.org/sqlite"
)

// Sqlite3Driver implement driver sqlite3 database/sql.
type Sqlite3Driver struct {
	*sqlite.Driver
}

type sqlite3DriverConn interface {
	Exec(string, []driver.Value) (driver.Result, error)
}

// Open is wrapper open the connection of sqlite driver.
func (d Sqlite3Driver) Open(name string) (conn driver.Conn, err error) {
	conn, err = d.Driver.Open(name)
	if err != nil {
		return
	}
	_, err = conn.(sqlite3DriverConn).Exec("PRAGMA foreign_keys = ON;", nil)
	if err != nil {
		err = conn.Close()
	}
	return
}
