// Package infrastructure is implements an adapter to talk to low-level modules.
// # This manifest was generated by ymir. DO NOT EDIT.
package infrastructure

import (
	"os"
	"strings"

	"github.com/mattn/go-colorable"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"

	"github.com/kubuskotak/asgard/tracer"
)

// InitializeLogger will set logging format.
func InitializeLogger(stage string) {
	zerolog.TimeFieldFormat = zerolog.TimeFormatUnix
	writer := &tracer.ZeroWriter{MinLevel: zerolog.DebugLevel}
	log.Logger = zerolog.New(
		zerolog.MultiLevelWriter(colorable.NewColorable(os.Stdout), writer)).
		With().Timestamp().Caller().Logger()
	if strings.EqualFold(stage, Development) {
		log.Logger = log.Output(zerolog.ConsoleWriter{Out: colorable.NewColorable(os.Stderr)})
	}
}
