// Package rest is port adapter via http/s protocol
// # This manifest was generated by ymir. DO NOT EDIT.
package rest

import (
	"errors"
	"net/http"
	"net/url"
)

// DefaultClientHttp is the default Client and is used by Get, Head, and Post.
type DefaultClientHttp struct {
	// BaseUrl is the base url to set on requests.
	BaseUrl *url.URL
	// Transport is the underlying HTTP transport.
	// If nil, http.DefaultTransport is used.
	Transport http.RoundTripper
}

// RoundTrip executes a single HTTP transaction, returning
// a Response for the provided Request.
func (c *DefaultClientHttp) RoundTrip(req *http.Request) (*http.Response, error) {
	rt := c.Transport
	if rt == nil {
		rt = http.DefaultTransport
		if rt == nil {
			return nil, errors.New("transport: no Transport specified or available")
		}
	}
	newReq := *req
	newReq.URL = c.BaseUrl.ResolveReference(req.URL)
	args := newReq.URL.Query()
	newReq.URL.RawQuery = args.Encode()
	return rt.RoundTrip(&newReq)
}
