// Package rest is port adapter via http/s protocol
// # This manifest was generated by ymir. DO NOT EDIT.
package rest

import (
	"net/http"
	"strings"
)

// ContentType - Custom type to hold value for find and replace on content type.
type ContentType int

// Declare related constants for each ContentType starting with index 1.
const (
	UnknownMedia ContentType = iota
	charsetUTF8
	MIMEApplicationJSON
	MIMEApplicationJSONCharsetUTF8
	MIMEApplicationJavaScript
	MIMEApplicationJavaScriptCharsetUTF8
	MIMEApplicationXML
	MIMEApplicationXMLCharsetUTF8
	MIMETextXML
	MIMETextXMLCharsetUTF8
	MIMEApplicationForm
	MIMEApplicationProtobuf
	MIMEApplicationMsgpack
	MIMETextCSV
	MIMETextCSVCharsetUTF8
	MIMETextHTML
	MIMETextHTMLCharsetUTF8
	MIMETextPlain
	MIMETextPlainCharsetUTF8
	MIMETextJavaScript
	MIMETextJavaScriptCharsetUTF8
	MIMEMultipartForm
	MIMEOctetStream
	MIMEImageJPEG
	MIMEImagePNG
)

// String - Creating common behavior - give the type a String function.
func (m ContentType) String() string {
	return [...]string{
		"text/unknown",
		"charset=UTF-8",
		"application/json",
		"application/json;charset=UTF-8",
		"application/javascript",
		"application/javascript;charset=UTF-8",
		"application/xml",
		"application/xml;charset=UTF-8",
		"text/xml",
		"text/xml;charset=UTF-8",
		"application/x-www-form-urlencoded",
		"application/protobuf",
		"application/msgpack",
		"text/csv",
		"text/csv;charset=UTF-8",
		"text/html",
		"text/html;charset=UTF-8",
		"text/plain",
		"text/plain;charset=UTF-8",
		"text/javascript",
		"text/javascript;charset=UTF-8",
		"multipart/form-data",
		"application/octet-stream",
		"image/jpeg",
		"image/png",
	}[m]
}

// Index - Return index of the Constant.
func (m ContentType) Index() int {
	return int(m)
}

// GetRequestContentType is a helper function that returns ContentType based on
// context or request headers.
func GetRequestContentType(r *http.Request) ContentType {
	s := strings.TrimSpace(strings.Split(r.Header.Get(HeaderContentType.String()), ";")[0])
	switch s {
	case MIMETextPlain.String():
		return MIMETextPlain
	case MIMETextHTML.String():
		return MIMETextHTML
	case MIMEApplicationJSON.String(), MIMETextJavaScript.String():
		return MIMEApplicationJSON
	case MIMETextXML.String(), MIMEApplicationXML.String():
		return MIMETextXML
	case MIMEApplicationForm.String():
		return MIMEApplicationForm
	case MIMEMultipartForm.String():
		return MIMEMultipartForm
	case MIMEOctetStream.String():
		return MIMEOctetStream
	default:
		return UnknownMedia
	}
}
