// Package rest is port adapter via http/s protocol
// # This manifest was generated by ymir. DO NOT EDIT.
package rest

// HeaderType - Custom type to hold value for find and replace on header type.
type HeaderType int

const (
	HeaderAuthorization HeaderType = iota
	HeaderContentDisposition
	HeaderContentEncoding
	HeaderContentLength
	HeaderContentType
	HeaderContentDesc
	HeaderCookie
	HeaderXCSRFToken
	HeaderAccessControlAllowOrigin
	HeaderXTraceId
	HeaderUberTraceId
	HeaderContentTypeOptions
)

// String - Creating common behavior - give the type a String function.
func (h HeaderType) String() string {
	return [...]string{
		"Authorization",
		"Content-Disposition",
		"Content-Encoding",
		"Content-Length",
		"Content-Type",
		"Content-Description",
		"Cookie",
		"X-CSRF-Token",
		"Access-Control-Allow-Origin",
		"X-Trace-Id",
		"Uber-Trace-Id",
		"X-Content-Type-Options",
	}[h]
}

// Index - Return index of the Constant.
func (h HeaderType) Index() int {
	return int(h)
}
