// Package rest is port adapter via http/s protocol
// # This manifest was generated by ymir. DO NOT EDIT.
package rest

import (
	"errors"
	"net/http"
)

// RequestType - Custom type to hold value for find and replace on context value request type.
type RequestType int

// CtxPayloadRequest Declare related constants for each RequestType starting with index 1.
const CtxPayloadRequest RequestType = iota

// GetBind send a Pagination data.
func GetBind[T any](r *http.Request) (T, error) {
	var zero T
	payload, ok := r.Context().Value(CtxPayloadRequest).(T)
	if !ok {
		return zero, errors.New("request payload is not found")
	}
	return payload, nil
}
